default: &default
  adapter: postgresql
  encoding: unicode
  username: pja-rss
  password: pja-rss
  pool: 5

development:
  <<: *default
  database: pjarss_development

test:
  <<: *default
  database: pjarss_test
