# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e252db37899d36488cb38a02006123b1470c510844e74298986bd29ce0cd7eb4aaf63841b5875b86c31bc6b66a05a12ba5f6686cc33345915aefccdf85848ce

test:
  secret_key_base: cbdd9641f33834e7f243778976e0e51f3def4d398c461275f476783ce0ae5effef052e76ee6ba6aca26d58181bc26a163f60bf51e977c49e326132b66243895d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
